### ISSUE TITLE
Console error, wondering what it means

### ISSUE THREAD

**Issue by TheZenKitteh** [mushroomhostage/SilkSpawners#6]
Just wondering what this error means:

08.08 22:07:51 [Server] WARN [SilkSpawners] Reflection failed: spawner 
08.08 22:07:51 [Server] WARN java.lang.NoSuchFieldException: spawner 
08.08 22:07:51 [Server] WARN at java.lang.Class.getDeclaredField(Class.java:2070) 
08.08 22:07:51 [Server] WARN at de.dustplanet.silkspawners.compat.v1_12_R1.NMSHandler.<init>(NMSHandler.java:46) 
08.08 22:07:51 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
08.08 22:07:51 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 
08.08 22:07:51 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
08.08 22:07:51 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
08.08 22:07:51 [Server] WARN at de.dustplanet.util.SilkUtil.setupNMSProvider(SilkUtil.java:145) 
08.08 22:07:51 [Server] WARN at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:118) 
08.08 22:07:51 [Server] WARN at de.dustplanet.silkspawners.SilkSpawners.onEnable(SilkSpawners.java:87) 
08.08 22:07:51 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) 
08.08 22:07:51 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) 
08.08 22:07:51 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) 
08.08 22:07:51 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:380) 
08.08 22:07:51 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) 
08.08 22:07:51 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) 
08.08 22:07:51 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) 
08.08 22:07:51 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) 
08.08 22:07:51 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) 
08.08 22:07:51 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) 
08.08 22:07:51 [Server] WARN at java.lang.Thread.run(Thread.java:745)

**Comment by timbru31** [comment]
Hi @TheZenKitteh, this is actually the old/dead project from the original author. The issue you are describing has been reported here: https://github.com/timbru31/SilkSpawners/issues/92 - in other words: update your Spigot and use a dev build, v5.0.0 will come out soon.
